version: '3.8'

services:
  nestjs-10:
    container_name: nestjs-10-dev
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - '3000:3000'
    env_file:
      - ./.env

  postgres:
    container_name: postgres-dev
    image: postgres:16
    restart: always
    env_file:
      - ./.env
    volumes:
      - postgres_data_dev:/var/lib/postgresql/data

volumes:
  postgres_data_dev:
