version: '3.8'

services:
  postgres:
    container_name: postgres-dev
    image: postgres:16
    restart: always
    ports:
      - '${POSTGRES_EXTERNAL_PORT}:${POSTGRES_INTERNAL_PORT}'
    env_file:
      - ./.env
    volumes:
      - postgres_data_dev:/var/lib/postgresql/data

volumes:
  postgres_data_dev:
