version: '3.8'

services:
  nestjs-10:
    container_name: nestjs-10-prod
    build:
      context: .
      dockerfile: Dockerfile.prod
    ports:
      - '${NEST_EXTERNAL_PORT}:${NEST_INTERNAL_PORT}'
    env_file:
      - ./.env.prod

  postgres:
    container_name: postgres-prod
    image: postgres:16
    restart: always
    ports:
      - '${POSTGRES_EXTERNAL_PORT}:${POSTGRES_INTERNAL_PORT}'
    env_file:
      - ./.env.prod
    volumes:
      - postgres_data_prod:/var/lib/postgresql/data

volumes:
  postgres_data_prod:
