version: '3.8'

services:
  nestjs-10:
    container_name: nestjs-10-prod
    build:
      context: .
      dockerfile: Dockerfile.prod
    ports:
      - '3000:3000'
    env_file:
      - ./.env.prod

  postgres:
    container_name: postgres-prod
    image: postgres:latest
    restart: always
    env_file:
      - ./.env.prod
    volumes:
      - postgres_data_prod:/var/lib/postgresql/data

volumes:
  postgres_data_prod:
